// <auto-generated />
using System;
using DietApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250122194235_PatientMigration")]
    partial class PatientMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DietApp.Data.DietUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GraduationSertificatePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranskriptPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DietUser");
                });

            modelBuilder.Entity("DietApp.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlergyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("DietApp.Entities.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiseaseName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiseaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("DietApp.Entities.EatingHabit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsumedFoods")
                        .HasColumnType("TEXT");

                    b.Property<string>("CookingMethod")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DailyMealCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DessertConsumption")
                        .HasColumnType("TEXT");

                    b.Property<string>("EatingDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("EatingOutHabits")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodIntolerances")
                        .HasColumnType("TEXT");

                    b.Property<string>("MealTimes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnackingHabits")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WaterConsumption")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EatingHabits");
                });

            modelBuilder.Entity("DietApp.Entities.FamilyDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiseaseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FamilyDiseases");
                });

            modelBuilder.Entity("DietApp.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthIssuesManagement")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherGoals")
                        .HasColumnType("TEXT");

                    b.Property<string>("SportsPerformanceGoals")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightGoal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("DietApp.Entities.Lifestyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlcoholConsumption")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaffeineIntake")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberOfSmokingPackage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmokingHabits")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmokingUtilezeYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSupport")
                        .HasColumnType("TEXT");

                    b.Property<string>("StressLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Lifestyles");
                });

            modelBuilder.Entity("DietApp.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("DietApp.Entities.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInformation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfChildren")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PersonalInfos");
                });

            modelBuilder.Entity("DietApp.Entities.PhysicalActivityStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DailyInactivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegularPhysicalActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("SleepPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PhysicalActivityStatus");
                });

            modelBuilder.Entity("DietApp.Entities.Allergy", b =>
                {
                    b.HasOne("DietApp.Data.DietUser", "User")
                        .WithMany("Allergies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.Disease", b =>
                {
                    b.HasOne("DietApp.Data.DietUser", "User")
                        .WithMany("Diseases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.EatingHabit", b =>
                {
                    b.HasOne("DietApp.Data.DietUser", "User")
                        .WithOne("EatingHabit")
                        .HasForeignKey("DietApp.Entities.EatingHabit", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.FamilyDisease", b =>
                {
                    b.HasOne("DietApp.Data.DietUser", "User")
                        .WithMany("FamilyDiseases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.Goal", b =>
                {
                    b.HasOne("DietApp.Data.DietUser", "User")
                        .WithOne("Goal")
                        .HasForeignKey("DietApp.Entities.Goal", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.Lifestyle", b =>
                {
                    b.HasOne("DietApp.Data.DietUser", "User")
                        .WithOne("Lifestyle")
                        .HasForeignKey("DietApp.Entities.Lifestyle", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.Medication", b =>
                {
                    b.HasOne("DietApp.Data.DietUser", "User")
                        .WithMany("Medications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.PersonalInfo", b =>
                {
                    b.HasOne("DietApp.Data.DietUser", "User")
                        .WithOne("PersonalInfo")
                        .HasForeignKey("DietApp.Entities.PersonalInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.PhysicalActivityStatus", b =>
                {
                    b.HasOne("DietApp.Data.DietUser", "User")
                        .WithOne("PhysicalActivityStatus")
                        .HasForeignKey("DietApp.Entities.PhysicalActivityStatus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Data.DietUser", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Diseases");

                    b.Navigation("EatingHabit");

                    b.Navigation("FamilyDiseases");

                    b.Navigation("Goal");

                    b.Navigation("Lifestyle");

                    b.Navigation("Medications");

                    b.Navigation("PersonalInfo");

                    b.Navigation("PhysicalActivityStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
